// Code generated by "stringer -type=NitroRequestType -output=nitroRequestType_string.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NitroUnknownRequest-0]
}

const _NitroRequestType_name = "NitroUnknownRequest"

var _NitroRequestType_index = [...]uint8{0, 19}

func (i NitroRequestType) String() string {
	if i < 0 || i >= NitroRequestType(len(_NitroRequestType_index)-1) {
		return "NitroRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NitroRequestType_name[_NitroRequestType_index[i]:_NitroRequestType_index[i+1]]
}
