// Code generated by "stringer -type=NitroRequestMethod -output=nitroRequestMethod_string.go"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NitroUnknownMethod-0]
}

const _NitroRequestMethod_name = "NitroUnknownMethod"

var _NitroRequestMethod_index = [...]uint8{0, 18}

func (i NitroRequestMethod) String() string {
	if i < 0 || i >= NitroRequestMethod(len(_NitroRequestMethod_index)-1) {
		return "NitroRequestMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NitroRequestMethod_name[_NitroRequestMethod_index[i]:_NitroRequestMethod_index[i+1]]
}
